version: 2
jobs:
  install-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules/*


  deploy-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
    filters:
      tags:
        only: /v[0-9]+(\.[0-9]+)*/

  test-job:
    docker:
      # specify the version you desire here
      - image: circleci/node:9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
      - run: yarn flow

  build-job:
    docker:
      # specify the version you desire here
      - image: circleci/node:9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
        at: ~/repo
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist/*

workflows:
  version: 2
  build-deploy:
    jobs:
      - install-job
      - build-job:
          requires:
            - install-job
      - test-job:
          requires:
            - install-job
      - deploy-job:
          requires:
            - test-job
            - build-job
          filters:
            branches:
              only: master
            
